[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capital_program = "8syRdGBunFUWZzkgGigv1KWcTEhxPkc15DMVXEYj9qVn"
nft_program = "AkFAoXys2zhqE15q8XJJJRqXgxLdtJ1kb9ec4fCo1GgH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
depositRewards = "npx ts-node ./scripts/depositRewards.ts"
generate-clients = "bash codama/generate-clients.sh"
localnet = "solana-test-validator -r --bpf-program CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d core.so"
open = "npx ts-node ./scripts/open-vault.ts"
stake = "npx ts-node ./scripts/stake.ts"
test = "cargo test"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
